# coding: utf-8

"""
    Wheel Fitment API

    The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.  # noqa: E501

    OpenAPI spec version: v1
    Contact: info@wheel-size.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.make_model import MakeModel  # noqa: F401,E501
from swagger_client.models.model_with_trims import ModelWithTrims  # noqa: F401,E501


class MakeWithModels(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'make': 'MakeModel',
        'models': 'list[ModelWithTrims]'
    }

    attribute_map = {
        'make': 'make',
        'models': 'models'
    }

    def __init__(self, make=None, models=None):  # noqa: E501
        """MakeWithModels - a model defined in Swagger"""  # noqa: E501

        self._make = None
        self._models = None
        self.discriminator = None

        self.make = make
        self.models = models

    @property
    def make(self):
        """Gets the make of this MakeWithModels.  # noqa: E501


        :return: The make of this MakeWithModels.  # noqa: E501
        :rtype: MakeModel
        """
        return self._make

    @make.setter
    def make(self, make):
        """Sets the make of this MakeWithModels.


        :param make: The make of this MakeWithModels.  # noqa: E501
        :type: MakeModel
        """
        if make is None:
            raise ValueError("Invalid value for `make`, must not be `None`")  # noqa: E501

        self._make = make

    @property
    def models(self):
        """Gets the models of this MakeWithModels.  # noqa: E501


        :return: The models of this MakeWithModels.  # noqa: E501
        :rtype: list[ModelWithTrims]
        """
        return self._models

    @models.setter
    def models(self, models):
        """Sets the models of this MakeWithModels.


        :param models: The models of this MakeWithModels.  # noqa: E501
        :type: list[ModelWithTrims]
        """
        if models is None:
            raise ValueError("Invalid value for `models`, must not be `None`")  # noqa: E501

        self._models = models

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MakeWithModels):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
