# coding: utf-8

"""
    Wheel Fitment API

    The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.  # noqa: E501

    OpenAPI spec version: v1
    Contact: info@wheel-size.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.trim_with_market_and_years import TrimWithMarketAndYears  # noqa: F401,E501


class ModelWithTrims(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'slug': 'str',
        'name': 'str',
        'start_year': 'str',
        'end_year': 'str',
        'vehicles': 'list[TrimWithMarketAndYears]'
    }

    attribute_map = {
        'slug': 'slug',
        'name': 'name',
        'start_year': 'start_year',
        'end_year': 'end_year',
        'vehicles': 'vehicles'
    }

    def __init__(self, slug=None, name=None, start_year=None, end_year=None, vehicles=None):  # noqa: E501
        """ModelWithTrims - a model defined in Swagger"""  # noqa: E501

        self._slug = None
        self._name = None
        self._start_year = None
        self._end_year = None
        self._vehicles = None
        self.discriminator = None

        self.slug = slug
        self.name = name
        self.start_year = start_year
        self.end_year = end_year
        self.vehicles = vehicles

    @property
    def slug(self):
        """Gets the slug of this ModelWithTrims.  # noqa: E501

        Model name (e.g. `Outlander`)  # noqa: E501

        :return: The slug of this ModelWithTrims.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this ModelWithTrims.

        Model name (e.g. `Outlander`)  # noqa: E501

        :param slug: The slug of this ModelWithTrims.  # noqa: E501
        :type: str
        """
        if slug is None:
            raise ValueError("Invalid value for `slug`, must not be `None`")  # noqa: E501

        self._slug = slug

    @property
    def name(self):
        """Gets the name of this ModelWithTrims.  # noqa: E501

        Model slug name (e.g. `outlander`)  # noqa: E501

        :return: The name of this ModelWithTrims.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ModelWithTrims.

        Model slug name (e.g. `outlander`)  # noqa: E501

        :param name: The name of this ModelWithTrims.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def start_year(self):
        """Gets the start_year of this ModelWithTrims.  # noqa: E501

        Model production start year. It should be 'integer' but it is used as 'string' by historical reasons.  # noqa: E501

        :return: The start_year of this ModelWithTrims.  # noqa: E501
        :rtype: str
        """
        return self._start_year

    @start_year.setter
    def start_year(self, start_year):
        """Sets the start_year of this ModelWithTrims.

        Model production start year. It should be 'integer' but it is used as 'string' by historical reasons.  # noqa: E501

        :param start_year: The start_year of this ModelWithTrims.  # noqa: E501
        :type: str
        """
        if start_year is None:
            raise ValueError("Invalid value for `start_year`, must not be `None`")  # noqa: E501

        self._start_year = start_year

    @property
    def end_year(self):
        """Gets the end_year of this ModelWithTrims.  # noqa: E501

        Model production end year. It should be 'integer' but it is used as 'string' by  historical reasons.  It equals to the __*`current year + 1`*__ if it is still in production.  # noqa: E501

        :return: The end_year of this ModelWithTrims.  # noqa: E501
        :rtype: str
        """
        return self._end_year

    @end_year.setter
    def end_year(self, end_year):
        """Sets the end_year of this ModelWithTrims.

        Model production end year. It should be 'integer' but it is used as 'string' by  historical reasons.  It equals to the __*`current year + 1`*__ if it is still in production.  # noqa: E501

        :param end_year: The end_year of this ModelWithTrims.  # noqa: E501
        :type: str
        """
        if end_year is None:
            raise ValueError("Invalid value for `end_year`, must not be `None`")  # noqa: E501

        self._end_year = end_year

    @property
    def vehicles(self):
        """Gets the vehicles of this ModelWithTrims.  # noqa: E501


        :return: The vehicles of this ModelWithTrims.  # noqa: E501
        :rtype: list[TrimWithMarketAndYears]
        """
        return self._vehicles

    @vehicles.setter
    def vehicles(self, vehicles):
        """Sets the vehicles of this ModelWithTrims.


        :param vehicles: The vehicles of this ModelWithTrims.  # noqa: E501
        :type: list[TrimWithMarketAndYears]
        """
        if vehicles is None:
            raise ValueError("Invalid value for `vehicles`, must not be `None`")  # noqa: E501

        self._vehicles = vehicles

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelWithTrims):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
