# coding: utf-8

"""
    Wheel Fitment API

    The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.  # noqa: E501

    OpenAPI spec version: v1
    Contact: info@wheel-size.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.aggregation import Aggregation  # noqa: F401,E501
from swagger_client.models.size_aggregation import SizeAggregation  # noqa: F401,E501


class TiresAggregation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aspect_ratio': 'Aggregation',
        'diameter': 'Aggregation',
        'width': 'Aggregation',
        'tire_size': 'SizeAggregation'
    }

    attribute_map = {
        'aspect_ratio': 'aspect_ratio',
        'diameter': 'diameter',
        'width': 'width',
        'tire_size': 'tire_size'
    }

    def __init__(self, aspect_ratio=None, diameter=None, width=None, tire_size=None):  # noqa: E501
        """TiresAggregation - a model defined in Swagger"""  # noqa: E501

        self._aspect_ratio = None
        self._diameter = None
        self._width = None
        self._tire_size = None
        self.discriminator = None

        self.aspect_ratio = aspect_ratio
        self.diameter = diameter
        self.width = width
        self.tire_size = tire_size

    @property
    def aspect_ratio(self):
        """Gets the aspect_ratio of this TiresAggregation.  # noqa: E501


        :return: The aspect_ratio of this TiresAggregation.  # noqa: E501
        :rtype: Aggregation
        """
        return self._aspect_ratio

    @aspect_ratio.setter
    def aspect_ratio(self, aspect_ratio):
        """Sets the aspect_ratio of this TiresAggregation.


        :param aspect_ratio: The aspect_ratio of this TiresAggregation.  # noqa: E501
        :type: Aggregation
        """
        if aspect_ratio is None:
            raise ValueError("Invalid value for `aspect_ratio`, must not be `None`")  # noqa: E501

        self._aspect_ratio = aspect_ratio

    @property
    def diameter(self):
        """Gets the diameter of this TiresAggregation.  # noqa: E501


        :return: The diameter of this TiresAggregation.  # noqa: E501
        :rtype: Aggregation
        """
        return self._diameter

    @diameter.setter
    def diameter(self, diameter):
        """Sets the diameter of this TiresAggregation.


        :param diameter: The diameter of this TiresAggregation.  # noqa: E501
        :type: Aggregation
        """
        if diameter is None:
            raise ValueError("Invalid value for `diameter`, must not be `None`")  # noqa: E501

        self._diameter = diameter

    @property
    def width(self):
        """Gets the width of this TiresAggregation.  # noqa: E501


        :return: The width of this TiresAggregation.  # noqa: E501
        :rtype: Aggregation
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this TiresAggregation.


        :param width: The width of this TiresAggregation.  # noqa: E501
        :type: Aggregation
        """
        if width is None:
            raise ValueError("Invalid value for `width`, must not be `None`")  # noqa: E501

        self._width = width

    @property
    def tire_size(self):
        """Gets the tire_size of this TiresAggregation.  # noqa: E501


        :return: The tire_size of this TiresAggregation.  # noqa: E501
        :rtype: SizeAggregation
        """
        return self._tire_size

    @tire_size.setter
    def tire_size(self, tire_size):
        """Sets the tire_size of this TiresAggregation.


        :param tire_size: The tire_size of this TiresAggregation.  # noqa: E501
        :type: SizeAggregation
        """
        if tire_size is None:
            raise ValueError("Invalid value for `tire_size`, must not be `None`")  # noqa: E501

        self._tire_size = tire_size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TiresAggregation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
