# coding: utf-8

"""
    Wheel Fitment API

    The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.  # noqa: E501

    OpenAPI spec version: v1
    Contact: info@wheel-size.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BoltPattern(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pattern': 'str',
        'stud': 'int',
        'pcd': 'float',
        'count': 'int'
    }

    attribute_map = {
        'pattern': 'pattern',
        'stud': 'stud',
        'pcd': 'pcd',
        'count': 'count'
    }

    def __init__(self, pattern=None, stud=None, pcd=None, count=None):  # noqa: E501
        """BoltPattern - a model defined in Swagger"""  # noqa: E501

        self._pattern = None
        self._stud = None
        self._pcd = None
        self._count = None
        self.discriminator = None

        if pattern is not None:
            self.pattern = pattern
        if stud is not None:
            self.stud = stud
        if pcd is not None:
            self.pcd = pcd
        if count is not None:
            self.count = count

    @property
    def pattern(self):
        """Gets the pattern of this BoltPattern.  # noqa: E501

        Formatted bolt pattern (e.g. `5x105`)  # noqa: E501

        :return: The pattern of this BoltPattern.  # noqa: E501
        :rtype: str
        """
        return self._pattern

    @pattern.setter
    def pattern(self, pattern):
        """Sets the pattern of this BoltPattern.

        Formatted bolt pattern (e.g. `5x105`)  # noqa: E501

        :param pattern: The pattern of this BoltPattern.  # noqa: E501
        :type: str
        """

        self._pattern = pattern

    @property
    def stud(self):
        """Gets the stud of this BoltPattern.  # noqa: E501

        Stud holes number (e.g. `5`)  # noqa: E501

        :return: The stud of this BoltPattern.  # noqa: E501
        :rtype: int
        """
        return self._stud

    @stud.setter
    def stud(self, stud):
        """Sets the stud of this BoltPattern.

        Stud holes number (e.g. `5`)  # noqa: E501

        :param stud: The stud of this BoltPattern.  # noqa: E501
        :type: int
        """

        self._stud = stud

    @property
    def pcd(self):
        """Gets the pcd of this BoltPattern.  # noqa: E501

        Pitch circle diameter, mm (e.g. `105`)  # noqa: E501

        :return: The pcd of this BoltPattern.  # noqa: E501
        :rtype: float
        """
        return self._pcd

    @pcd.setter
    def pcd(self, pcd):
        """Sets the pcd of this BoltPattern.

        Pitch circle diameter, mm (e.g. `105`)  # noqa: E501

        :param pcd: The pcd of this BoltPattern.  # noqa: E501
        :type: float
        """

        self._pcd = pcd

    @property
    def count(self):
        """Gets the count of this BoltPattern.  # noqa: E501

        Number of vehicles matching bolt pattern  # noqa: E501

        :return: The count of this BoltPattern.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this BoltPattern.

        Number of vehicles matching bolt pattern  # noqa: E501

        :param count: The count of this BoltPattern.  # noqa: E501
        :type: int
        """

        self._count = count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BoltPattern):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
